### PR TITLE
Emmet test branch

### PR DESCRIPTION
**Pull request by l00144427**
Adding a documentation folder & inside it putting a requirements document.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
is "content" folder where documentation goes?

**Comment by l00144427** [comment]
I put a new folder under Doodle called documentation, maybe that folder should have gone inside the content folder?

**Comment by ghost** [comment]
cool, maybe someone else can confirm, but i think "content" is the documentation folder already.

**Review by ghost — APPROVED** [review]
lgtm

**Comment by ghost** [comment]
you could also link this in top level readme

**Review by L00144438 — APPROVED** [review]

**Review by cjfarrelly — CHANGES_REQUESTED** [review]
Rename the file to 'requirements.md' and put it in contents folder

**Comment by cjfarrelly** [comment]
As @peterti pointed out, link it from the readme as well :-)

**Pull request closed without merging**
