### PR TITLE
Cdorrian

### PR DESCRIPTION
**Pull request by ConorDorrian1**

### CODE REVIEW

**Comment by ghost** [comment]
this is the same as before?

**Comment by ConorDorrian1** [comment]
> this is the same as before?

yea, Wes told me to tidy it and when I did it mucked up my environment haha

**Comment by ghost** [comment]
doesnt look any tidier :D

**Comment by ConorDorrian1** [comment]
> doesnt look any tidier :D

I just need it approved to get rid of it haha dont know how to clear all that shite above

**Comment by ghost** [comment]
i think maybe you can try rebasing

but tbh prob just easier to copy your work, blow away your local clone and start fresh

**Comment by ConorDorrian1** [comment]
> i think maybe you can try rebasing
> 
> but tbh prob just easier to copy your work, blow away your local clone and start fresh

I done that and it fecked up and created a new one but the changes were still there

**Pull request closed without merging**
