### PR TITLE
adding a file on how to set mongo up using the terminal/cmd and a few…

### PR DESCRIPTION
**Pull request by ConorDorrian1**
… basic commands to get started

### CODE REVIEW

**Review by l00073976 — APPROVED** [review]
lgtm

**Review by l00144427 — CHANGES_REQUESTED** [review]
Can you put in the link from where you downloaded MongoDB, just to make sure we're all using the same version?

**Comment by ConorDorrian1** [comment]
> 
> 
> Can you put in the link from where you downloaded MongoDB, just to make sure we're all using the same version?

sure

**Comment by ConorDorrian1** [comment]
> 
> 
> > Can you put in the link from where you downloaded MongoDB, just to make sure we're all using the same version?
> 
> sure

Can you re-review it again please. Thanks

**Review by l00144427 — APPROVED** [review]
Changes look good

**Pull request merged**
